repos:
  - repo: local
    hooks:
      - id: readycpp-tests
        name: Validation des tests unitaires c++
        entry: hooks/pre-commit/cmd/readycpp-cpp-tests.sh
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: readycpp-bash-tests
        name: Validation des tests unitaires bash
        entry: hooks/pre-commit/cmd/readycpp-bash-tests.sh
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/GitGuardian/ggshield
    rev: v1.53.0
    hooks:
      - id: ggshield

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        args: ["-style=file"]
        files: "\\.(c|cpp|h|hpp)$"
