repos:
  - repo: local
    hooks:
      - id: readycpp-bash-tests
        name: Validation des tests unitaires bash
        entry: hooks/pre-commit/readycpp-bash-tests.sh
        language: system
        pass_filenames: false
